dist: bionic
language: go
go:
  - 1.12.17
  - 1.14.4
install:
  - go get github.com/chai2010/gettext-go
script:
  - go test -v gettext.go gettext_test.go
  - go test -v gettext.go parse.go parse_test.go
